export { default as Navbar } from './Navbar/Navbar'
export { default as Header } from './header/Header'
export { default as About } from './aboutMe/About'
export { ShoppingCart as ShoppingCart } from './shoppingCart/ShoppingCart'
export { Counter as Counter } from './counter/Counter'
